FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn package -DskipTests

FROM eclipse-temurin:21
WORKDIR /app
COPY --from=build /app/target /app/target
EXPOSE 8080
CMD ["java", "-jar", "/app/target/quarkus-app/quarkus-run.jar"]
