services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: unifor
      POSTGRES_PASSWORD: unifor
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
      - ./Database:/docker-entrypoint-initdb.d:z
    networks:
      - dev_net

  backend:
    build:
      context: ./student-manager-backend
      dockerfile: Dockerfile
    container_name: quarkus_backend
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_USERNAME: unifor
      QUARKUS_DATASOURCE_PASSWORD: unifor
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/master
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "8089:8080"
    networks:
      - dev_net

  frontend:
    build:
      context: ./student-manager-frontend
    container_name: angular_frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - dev_net

networks:
  dev_net:
    driver: bridge
