CREATE TABLE USUARIO (
    ID_USUARIO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    IS_ATIVO BOOLEAN
);
