CREATE TABLE ALUNO (
    ID_ALUNO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MATRICULA VARCHAR(20) UNIQUE NOT NULL,
    ID_USUARIO BIGINT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
